version: "3.8"

services:
  db_server:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sisdb2025
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Permitir contraseñas vacías para root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80" # PhpMyAdmin se abrirá en localhost:8080
    environment:
      PMA_HOST: db_server
    depends_on:
      - db_server

  micro_transaccion:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002" # Usa el puerto 8002 para el microservicio de transacciones
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_server:3306/sisdb2025
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db_server

volumes:
  db_data:
